spring:
  rabbitmq:
    addresses: 'ip'
    username: 'guest'
    password: 'guest'  
  sleuth:
    enabled : true
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl:  '@zipkin.server.url@'
    enabled : false
  application:
    name: 'content-turbine'
  cloud:
    consul:
        host: 'localhost'
        port: 8500
        discovery:
          healthCheckPath: '/test/healthcheck'      
  jackson:
    serialization-inclusion: NON_EMPTY
endpoints:
  prometheus:
    enable: true
  health:
    sensitive: false
    time-to-live: 100
server:
  contextPath: /api/turbine
  port: '9898'
turbine:
  appConfig: content-context
  instanceUrlSuffix: /api/contextService/hystrix.stream
  clusterNameExpression: new String("default")
management:
  endpoints:
    web:
      path-mapping: /
  security:
    enabled: false  
  